# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 研究室について
    url: tour
    weight: 10
  - name: お知らせ
    url: post
    weight: 20
  - name: メンバー
    url: people
    weight: 30
  - name: イベント
    url: event
    weight: 40
  - name: 業績
    url: publication
    weight: 50
  - name: アクセス
    url: contact
    weight: 60
